services:
  nginx:
    image: nginx:latest

x-uffizzi:
  ingress:
    service: nginx
    port: 80

  continuous_preview:
    delete_preview_after: 2h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
