services:
  hello-world:
    image: gcr.io/uffizzi-pro-qa-gke/e8r8-3d6f93717f:c5261c773f050eeeaf6f19e30eca8bda003ef8a6

x-uffizzi:
  ingress:
    service: hello-world
    port: 80

  continuous_preview:
    delete_preview_after: 96h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
