services:
  hello-world:
    build: 
      context: https://github.com/moklidia/hello-world-1#compose-test
      dockerfile: Dockerfile

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true
